"""added nullable for fos

Revision ID: 3a55d6f1220b
Revises: 7d6d3501c0b6
Create Date: 2023-07-11 12:20:06.844354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a55d6f1220b'
down_revision = '7d6d3501c0b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scientists', schema=None) as batch_op:
        batch_op.alter_column('field_of_study',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scientists', schema=None) as batch_op:
        batch_op.alter_column('field_of_study',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
